name = "mhbuilder-cms"

compatibility_date = "2026-08-04"

pages_build_output_dir = ".next"

[vars]
APP_NAME = "MHBuilder Lahore"
APP_URL = "https://your-domain.com"

[[d1_databases]]
binding = "DB"
database_name = "mhbuilder-d1"
database_id = "PASTE_YOUR_D1_DATABASE_ID"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "mhbuilder-r2"
